- Sample 50/50 tumor/normal
- center_4 for testing
- ~~center_1 for validation (split in two parts)~~
- ~~center_0 + center_2 + center_3 for training~~

*updated 26.06.2019*

- centers 0 - 3 for training with 4-fold cross-validation (center per fold)

In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm_notebook

In [2]:
sampling_seed = 12358

In [4]:
df0 = pd.read_csv('data/training/center_0.csv').set_index('Unnamed: 0')
df0.head()

,patchId,fileName,center,patient,node,centerX,centerY,isTumor,tumorPercentage,tissuePercentage,meanHue,meanSaturation,meanValue,tumorLabel
Unnamed: 0,,,,,,,,,,,,,,
0,19000414720061184,data/training/center_0/patient_019_node_4.tif,0,19,4,41472,61184,False,0.0,29.6,0.76,0.03,0.95,False
1,19000416000061312,data/training/center_0/patient_019_node_4.tif,0,19,4,41600,61312,False,0.0,36.3,0.77,0.03,0.95,False
2,19000418560061568,data/training/center_0/patient_019_node_4.tif,0,19,4,41856,61568,False,0.0,51.5,0.74,0.03,0.96,False
3,19000418560062848,data/training/center_0/patient_019_node_4.tif,0,19,4,41856,62848,False,0.0,67.9,0.74,0.02,0.96,False
4,19000417280062976,data/training/center_0/patient_019_node_4.tif,0,19,4,41728,62976,False,0.0,36.7,0.78,0.00,0.97,False

In [6]:
def sample_df(df, random_seed):
    df_tumor = df[df['tumorLabel'] == True]
    df_normal = df[df['tumorLabel'] == False]
    tumor_count = len(df_tumor)
    # sample randomly the same amount of normals
    df_normal_sample = df_normal.sample(tumor_count, random_state=random_seed)
    # combine and shuffle
    df_combined = pd.concat([df_tumor, df_normal_sample], ignore_index=True)
    # this shuffles
    return df_combined.sample(frac=1, random_state=random_seed + 1)

In [11]:
df0_sample = sample_df(df0, sampling_seed)
df0_sample.describe(include='all')

,patchId,fileName,center,patient,node,centerX,centerY,isTumor,tumorPercentage,tissuePercentage,meanHue,meanSaturation,meanValue,tumorLabel
count,2.594800e+04,25948,25948.0,25948.000000,25948.000000,25948.000000,25948.000000,25948,25948.000000,25948.000000,25948.000000,25948.000000,25948.000000,25948
unique,NaN,100,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,2
top,NaN,data/training/center_0/patient_012_node_0.tif,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True
freq,NaN,6043,NaN,NaN,NaN,NaN,NaN,12980,NaN,NaN,NaN,NaN,NaN,12974
mean,1.214316e+16,NaN,0.0,12.142092,1.456259,106826.457839,38619.229844,NaN,49.586712,94.460725,0.782768,0.162542,0.752937,NaN
std,4.813439e+15,NaN,0.0,4.813375,1.335692,32573.715027,18084.622558,NaN,49.633234,16.806714,0.032093,0.071694,0.107153,NaN
min,2.892801e+11,NaN,0.0,0.000000,0.000000,5760.000000,1024.000000,NaN,0.000000,0.300000,0.570000,0.000000,0.000000,NaN
25%,1.000076e+16,NaN,0.0,10.000000,0.000000,87040.000000,23168.000000,NaN,0.000000,100.000000,0.770000,0.130000,0.680000,NaN
50%,1.200106e+16,NaN,0.0,12.000000,1.000000,103168.000000,36608.000000,NaN,67.500000,100.000000,0.790000,0.170000,0.750000,NaN
75%,1.600110e+16,NaN,0.0,16.000000,2.000000,138112.000000,52608.000000,NaN,99.900000,100.000000,0.800000,0.200000,0.810000,NaN
max,1.900142e+16,NaN,0.0,19.000000,4.000000,194048.000000,93312.000000,NaN,99.900000,100.000000,0.910000,0.600000,0.990000,NaN

In [12]:
df1 = pd.read_csv('data/training/center_1.csv').set_index('Unnamed: 0')
df1_sample = sample_df(df1, sampling_seed)
df1_sample.describe(include='all')

,patchId,fileName,center,patient,node,centerX,centerY,isTumor,tumorPercentage,tissuePercentage,meanHue,meanSaturation,meanValue,tumorLabel
count,1.208400e+04,12084,12084.0,12084.000000,12084.000000,12084.000000,12084.000000,12084,12084.000000,12084.000000,12084.000000,12084.000000,12084.000000,12084
unique,NaN,100,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,2
top,NaN,data/training/center_1/patient_022_node_4.tif,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True
freq,NaN,3290,NaN,NaN,NaN,NaN,NaN,6045,NaN,NaN,NaN,NaN,NaN,6042
mean,2.716418e+16,NaN,1.0,27.163025,2.857911,115623.806687,52283.085071,NaN,48.718049,94.506049,0.806558,0.252902,0.631269,NaN
std,6.331264e+15,NaN,0.0,6.331283,1.357208,40341.216694,16548.041778,NaN,48.875745,16.905565,0.036053,0.111861,0.129243,NaN
min,2.000014e+16,NaN,1.0,20.000000,0.000000,4224.000000,1536.000000,NaN,0.000000,0.300000,0.530000,0.000000,0.000000,NaN
25%,2.200068e+16,NaN,1.0,22.000000,2.000000,82272.000000,42496.000000,NaN,0.000000,100.000000,0.780000,0.190000,0.560000,NaN
50%,2.400162e+16,NaN,1.0,24.000000,3.000000,118656.000000,54272.000000,NaN,70.650000,100.000000,0.800000,0.280000,0.620000,NaN
75%,3.400096e+16,NaN,1.0,34.000000,4.000000,153472.000000,65152.000000,NaN,99.900000,100.000000,0.830000,0.330000,0.680000,NaN
max,3.900188e+16,NaN,1.0,39.000000,4.000000,205824.000000,92032.000000,NaN,99.900000,100.000000,0.940000,0.690000,0.960000,NaN

In [13]:
df2 = pd.read_csv('data/training/center_2.csv').set_index('Unnamed: 0')
df2_sample = sample_df(df2, sampling_seed)
df2_sample.describe(include='all')

,patchId,fileName,center,patient,node,centerX,centerY,isTumor,tumorPercentage,tissuePercentage,meanHue,meanSaturation,meanValue,tumorLabel
count,3.724000e+04,37240,37240.0,37240.000000,37240.000000,37240.000000,37240.000000,37240,37240.000000,37240.000000,37240.000000,37240.000000,37240.000000,37240
unique,NaN,100,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,2
top,NaN,data/training/center_2/patient_051_node_2.tif,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True
freq,NaN,12707,NaN,NaN,NaN,NaN,NaN,18627,NaN,NaN,NaN,NaN,NaN,18620
mean,4.958851e+16,NaN,2.0,49.587997,2.077873,51719.207734,71978.039957,NaN,49.578802,91.617720,0.865328,0.338994,0.755837,NaN
std,4.601207e+15,NaN,0.0,4.601180,1.141887,22144.810640,32183.911660,NaN,49.628481,20.341883,0.039111,0.152979,0.078473,NaN
min,4.000002e+16,NaN,2.0,40.000000,0.000000,1280.000000,2048.000000,NaN,0.000000,0.300000,0.000000,0.000000,0.290000,NaN
25%,4.600050e+16,NaN,2.0,46.000000,1.000000,32896.000000,44800.000000,NaN,0.000000,100.000000,0.850000,0.240000,0.710000,NaN
50%,5.100057e+16,NaN,2.0,51.000000,2.000000,52736.000000,73088.000000,NaN,71.850000,100.000000,0.870000,0.370000,0.750000,NaN
75%,5.200028e+16,NaN,2.0,52.000000,3.000000,72192.000000,91776.000000,NaN,99.900000,100.000000,0.880000,0.440000,0.810000,NaN
max,5.900094e+16,NaN,2.0,59.000000,4.000000,103680.000000,176000.000000,NaN,99.900000,100.000000,0.990000,0.820000,0.920000,NaN

In [14]:
df3 = pd.read_csv('data/training/center_3.csv').set_index('Unnamed: 0')
df3_sample = sample_df(df3, sampling_seed)
df3_sample.describe(include='all')

,patchId,fileName,center,patient,node,centerX,centerY,isTumor,tumorPercentage,tissuePercentage,meanHue,meanSaturation,meanValue,tumorLabel
count,5.943800e+04,59438,59438.0,59438.000000,59438.000000,59438.000000,59438.000000,59438,59438.000000,59438.000000,59438.000000,59438.000000,59438.000000,59438
unique,NaN,100,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,2
top,NaN,data/training/center_3/patient_073_node_1.tif,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True
freq,NaN,22966,NaN,NaN,NaN,NaN,NaN,29735,NaN,NaN,NaN,NaN,NaN,29719
mean,7.108530e+16,NaN,3.0,71.083953,1.821310,134221.515394,39918.812881,NaN,49.671966,94.476638,0.769697,0.274101,0.711145,NaN
std,4.720741e+15,NaN,0.0,4.720684,1.300418,37773.498601,23319.852601,NaN,49.705079,16.797625,0.033603,0.113229,0.144015,NaN
min,6.000051e+16,NaN,3.0,60.000000,0.000000,2304.000000,1152.000000,NaN,0.000000,1.100000,0.010000,0.000000,0.000000,NaN
25%,6.800119e+16,NaN,3.0,68.000000,1.000000,100864.000000,19712.000000,NaN,0.000000,100.000000,0.750000,0.210000,0.630000,NaN
50%,7.300157e+16,NaN,3.0,73.000000,1.000000,150656.000000,34688.000000,NaN,70.350000,100.000000,0.760000,0.300000,0.720000,NaN
75%,7.300175e+16,NaN,3.0,73.000000,3.000000,164608.000000,62208.000000,NaN,99.900000,100.000000,0.780000,0.360000,0.790000,NaN
max,7.900203e+16,NaN,3.0,79.000000,4.000000,204672.000000,95488.000000,NaN,99.900000,100.000000,0.970000,0.670000,0.990000,NaN

In [15]:
df4 = pd.read_csv('data/training/center_4.csv').set_index('Unnamed: 0')
df4_sample = sample_df(df4, sampling_seed)
df4_sample.describe(include='all')

,patchId,fileName,center,patient,node,centerX,centerY,isTumor,tumorPercentage,tissuePercentage,meanHue,meanSaturation,meanValue,tumorLabel
count,9.186000e+03,9186,9186.0,9186.000000,9186.000000,9186.000000,9186.000000,9186,9186.000000,9186.000000,9186.000000,9186.000000,9186.000000,9186
unique,NaN,29,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,2
top,NaN,data/training/center_4/patient_099_node_4.tif,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True
freq,NaN,4597,NaN,NaN,NaN,NaN,NaN,4594,NaN,NaN,NaN,NaN,NaN,4593
mean,9.376711e+16,NaN,4.0,93.766819,2.984433,29481.454387,68807.914653,NaN,49.467342,95.918158,0.841077,0.246165,0.794976,NaN
std,6.575018e+15,NaN,0.0,6.575126,1.353267,21887.173150,25252.884704,NaN,49.535318,14.518326,0.034200,0.079146,0.045930,NaN
min,8.000004e+16,NaN,4.0,80.000000,0.000000,1920.000000,2176.000000,NaN,0.000000,4.200000,0.710000,0.030000,0.540000,NaN
25%,8.800054e+16,NaN,4.0,88.000000,2.000000,12928.000000,52128.000000,NaN,0.000000,100.000000,0.820000,0.200000,0.770000,NaN
50%,9.900006e+16,NaN,4.0,99.000000,4.000000,19712.000000,77952.000000,NaN,62.850000,100.000000,0.830000,0.260000,0.790000,NaN
75%,9.900015e+16,NaN,4.0,99.000000,4.000000,44000.000000,82688.000000,NaN,99.900000,100.000000,0.870000,0.300000,0.820000,NaN
max,9.900088e+16,NaN,4.0,99.000000,4.000000,95872.000000,152448.000000,NaN,99.900000,100.000000,0.940000,0.620000,0.930000,NaN

Save splits

In [18]:
# combine training sets
df_training = pd.concat([df0_sample, df2_sample, df3_sample], ignore_index=True)
df_training = df_training.sample(frac=1, random_state=sampling_seed)
df_training.describe(include='all')

,patchId,fileName,center,patient,node,centerX,centerY,isTumor,tumorPercentage,tissuePercentage,meanHue,meanSaturation,meanValue,tumorLabel
count,1.226260e+05,122626,122626.000000,122626.000000,122626.000000,122626.000000,122626.000000,122626,122626.000000,122626.000000,122626.000000,122626.000000,122626.000000,122626
unique,NaN,300,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,2
top,NaN,data/training/center_3/patient_073_node_1.tif,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True
freq,NaN,22966,NaN,NaN,NaN,NaN,NaN,61342,NaN,NaN,NaN,NaN,NaN,61313
mean,5.208467e+16,NaN,2.061504,52.083636,1.821979,103369.714873,49379.808393,NaN,49.625633,93.605053,0.801505,0.270202,0.733561,NaN
std,2.316456e+16,NaN,1.152106,23.164421,1.281149,48364.291651,29501.284722,NaN,49.666244,17.997696,0.055059,0.135300,0.121763,NaN
min,2.892801e+11,NaN,0.000000,0.000000,0.000000,1280.000000,1024.000000,NaN,0.000000,0.300000,0.000000,0.000000,0.000000,NaN
25%,4.200077e+16,NaN,2.000000,42.000000,1.000000,68096.000000,25856.000000,NaN,0.000000,100.000000,0.760000,0.160000,0.670000,NaN
50%,5.700058e+16,NaN,2.000000,57.000000,2.000000,98560.000000,44544.000000,NaN,71.850000,100.000000,0.790000,0.280000,0.740000,NaN
75%,7.300140e+16,NaN,3.000000,73.000000,3.000000,152320.000000,69632.000000,NaN,99.900000,100.000000,0.850000,0.370000,0.800000,NaN
max,7.900203e+16,NaN,3.000000,79.000000,4.000000,204672.000000,176000.000000,NaN,99.900000,100.000000,0.990000,0.820000,0.990000,NaN

In [19]:
#split validation set
df_val_1 = df1_sample[len(df1_sample)//2:]
df_val_2 = df1_sample[:len(df1_sample)//2]

In [20]:
df_val_1.describe(include='all')

,patchId,fileName,center,patient,node,centerX,centerY,isTumor,tumorPercentage,tissuePercentage,meanHue,meanSaturation,meanValue,tumorLabel
count,6.042000e+03,6042,6042.0,6042.000000,6042.000000,6042.000000,6042.000000,6042,6042.000000,6042.000000,6042.000000,6042.000000,6042.000000,6042
unique,NaN,100,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,2
top,NaN,data/training/center_1/patient_022_node_4.tif,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,False
freq,NaN,1634,NaN,NaN,NaN,NaN,NaN,3042,NaN,NaN,NaN,NaN,NaN,3044
mean,2.714598e+16,NaN,1.0,27.144820,2.864449,115760.132406,52235.355180,NaN,48.374131,94.447120,0.807411,0.252476,0.630723,NaN
std,6.328335e+15,NaN,0.0,6.328353,1.353200,40359.560009,16531.791007,NaN,48.889149,16.941952,0.035781,0.112367,0.130600,NaN
min,2.000014e+16,NaN,1.0,20.000000,0.000000,4224.000000,2176.000000,NaN,0.000000,3.100000,0.540000,0.000000,0.000000,NaN
25%,2.200068e+16,NaN,1.0,22.000000,2.000000,82432.000000,42368.000000,NaN,0.000000,100.000000,0.780000,0.190000,0.560000,NaN
50%,2.400164e+16,NaN,1.0,24.000000,3.000000,118656.000000,54272.000000,NaN,0.000000,100.000000,0.800000,0.280000,0.620000,NaN
75%,3.400096e+16,NaN,1.0,34.000000,4.000000,153568.000000,65152.000000,NaN,99.900000,100.000000,0.830000,0.340000,0.680000,NaN
max,3.900187e+16,NaN,1.0,39.000000,4.000000,205568.000000,92032.000000,NaN,99.900000,100.000000,0.940000,0.690000,0.960000,NaN

In [21]:
df_val_2.describe(include='all')

,patchId,fileName,center,patient,node,centerX,centerY,isTumor,tumorPercentage,tissuePercentage,meanHue,meanSaturation,meanValue,tumorLabel
count,6.042000e+03,6042,6042.0,6042.000000,6042.000000,6042.000000,6042.000000,6042,6042.000000,6042.000000,6042.000000,6042.000000,6042.000000,6042
unique,NaN,100,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,2
top,NaN,data/training/center_1/patient_022_node_4.tif,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,True
freq,NaN,1656,NaN,NaN,NaN,NaN,NaN,3045,NaN,NaN,NaN,NaN,NaN,3044
mean,2.718239e+16,NaN,1.0,27.181231,2.851374,115487.480967,52330.814962,NaN,49.061966,94.564978,0.805705,0.253328,0.631816,NaN
std,6.334662e+15,NaN,0.0,6.334684,1.361284,40325.744428,16565.507306,NaN,48.863964,16.870296,0.036305,0.111361,0.127881,NaN
min,2.000015e+16,NaN,1.0,20.000000,0.000000,8832.000000,1536.000000,NaN,0.000000,0.300000,0.530000,0.000000,0.100000,NaN
25%,2.200068e+16,NaN,1.0,22.000000,2.000000,81920.000000,42624.000000,NaN,0.000000,100.000000,0.780000,0.190000,0.560000,NaN
50%,2.400160e+16,NaN,1.0,24.000000,3.000000,118656.000000,54208.000000,NaN,75.900000,100.000000,0.800000,0.280000,0.630000,NaN
75%,3.400096e+16,NaN,1.0,34.000000,4.000000,153344.000000,65152.000000,NaN,99.900000,100.000000,0.830000,0.330000,0.680000,NaN
max,3.900188e+16,NaN,1.0,39.000000,4.000000,205824.000000,90624.000000,NaN,99.900000,100.000000,0.920000,0.620000,0.960000,NaN

In [22]:
# Save center df's
df_training.to_csv('data/training/training.csv')
df_val_1.to_csv('data/training/validation_1.csv')
df_val_2.to_csv('data/training/validation_2.csv')
df4_sample.to_csv('data/training/test.csv')

#### Combine training and validation sets

In [4]:
df_training = pd.read_csv('data/training/training.csv').set_index('Unnamed: 0')
df_val_1 = pd.read_csv('data/training/validation_1.csv').set_index('Unnamed: 0')
df_val_2 = pd.read_csv('data/training/validation_2.csv').set_index('Unnamed: 0')

In [5]:
df_train_val = pd.concat([df_training, df_val_1, df_val_2], ignore_index=True)
df_train_val.to_csv('data/training/train_val.csv')